### ISSUE TITLE
Directx11 Check

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#10]
https://forums.cncnet.org/index.php?topic=6881.msg49954#msg49954

Running Directx10 produces a crash

**Comment by Rampastring** [comment]
Considering how unpopular Vista is nowadays, I don't think it's worth focusing on it. Just tell players that they should keep their OS up to date with SP2 and Platform update.

**Comment by Rampastring** [comment]
A check for SP2 has been added to the latest version of the client shortcut executable (DTA.exe / TI_Launcher.exe / MentalOmegaClient.exe / CnCNetYRLauncher.exe),

**Comment by GrantBartlett** [comment]
@Rampastring You will need to send me this?

**Comment by Rampastring** [comment]
@GrantBartlett http://rampastring.cnc-comm.com/extra/DTA.exe
