### ISSUE TITLE
Game Lobby dropdown boxes drawn incorrectly.

### ISSUE THREAD

**Issue by Martin-Veskilt** [CnCNet/xna-cncnet-client#103]
Steps to reproduce:

    1. Enter either Skirmish or a self hosted Custom Game Lobby.
    2. The game mode dropdown box is incorrectly drawn.
    3. Select a game mode, and the box is correctly drawn.

Update: I've noticed that the "Game Speed", "Credits" and "Starting Units" dropdown boxes are drawn with this same glitch.

**YR Normal UI Theme - Bugged**
![YR Original - Bugged](https://user-images.githubusercontent.com/54605063/63813964-28631380-c927-11e9-9249-904adb669bf2.jpg)

**YR Normal UI Theme - After Selection**
![YR Original - Normal](https://user-images.githubusercontent.com/54605063/63813965-2bf69a80-c927-11e9-94da-e6ab60ba6388.jpg)

As you can see below this affects custom themes a bit more visually.

**YR Custom UI Theme - Bugged**
![YR Custom - Bugged](https://user-images.githubusercontent.com/54605063/63813993-4a5c9600-c927-11e9-8f26-ab9f12e04075.jpg)

**YR Custom UI Theme - After Selection**
![YR Custom - Normal](https://user-images.githubusercontent.com/54605063/63814001-521c3a80-c927-11e9-95da-8e741381bb1f.jpg)

**Comment by Rampastring** [comment]
This is partially a result of a configuration fault in CnCNet YR INI files. They have the dropdown height defined as 21, while the texture of the drop-down arrow is 22 pixels high. Rampastring.XNAUI sets the height to match the texture when the drop down is opened and closed.
