### ISSUE TITLE
Game creation dialogue loses it's border when tunnel server selection is used.

### ISSUE THREAD

**Issue by Martin-Veskilt** [CnCNet/xna-cncnet-client#104]
Steps to reproduce:

1. Enter CnCNet Lobby.
2. Click "create game".
3. The game creation dialogue will appear with a border drawn.
4. Click the "Advanced Options" button, the game creation dialogue will expand to show the tunnel server selection list and the dialogue border will disappear.

**Game creation dialogue initially**
<img width="416" alt="YR Game Creation - Border" src="https://user-images.githubusercontent.com/54605063/63814398-a542bd00-c928-11e9-9c35-aeecf4157bc3.png">

**Game creation dialogue expanded**
<img width="429" alt="YR Game Creation - Expanded No Border" src="https://user-images.githubusercontent.com/54605063/63814413-b2f84280-c928-11e9-8ce4-fae41109d824.png">

**Comment by dkeetonx** [comment]
Corrected.
