### ISSUE TITLE
Handle files that are unable to be opened due to permissions

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#106]
Just seen someone had this. Client should probably handle this gracefully.

https://media.discordapp.net/attachments/281167308569837568/617729770825973760/70129414_726638944463341_6550442695452524544_n.jpg?width=452&height=602

**Comment by Rampastring** [comment]
I think this should already be handled properly in the latest master. Reopen if that is determined not to be the case.
