### ISSUE TITLE
After the game the client doesn't maximise and I need do this manually from the taskbar

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#13]
After the game the client doesn't maximise and I need do this manually from the taskbar

https://forums.cncnet.org/index.php?topic=6884.0

**Comment by Rampastring** [comment]
The window is already returned to normal after a game:
https://github.com/CnCNet/xna-cncnet-client/blob/master/DXMainClient/DXGUI/Generic/GameInProgressWindow.cs#L133

And WindowManager.MaximizeWindow() changes the internal game window's WindowState to FormWindowState.Normal.
