### ISSUE TITLE
Being banned from a game and rejoining the same game stops you from joining other ones

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#130]
**Scenario:** 

- You've been kicked and banned (without knowing) by the game host. 
- You rejoin the same game
- You only realise you've been banned because the client doesn't allow you to join the game you've attempted to re-join. 
- The clients behaviour now locks you out from other game lobbies and only a client restart allows you join other games again.

**Discussion**: 
Should you even see the game you were banned from at all?

**Comment by Rampastring** [comment]
Should be checked whether https://github.com/CnCNet/xna-cncnet-client/commit/a2fe115983b0d5cb8a6b8a35bde0833de1bfd4ce fixed it

**Comment by Rampastring** [comment]
Confirmed as fixed by @Starkku .
