### ISSUE TITLE
How to set online game lobby server access point order list

### ISSUE THREAD

**Issue by Knighthana** [CnCNet/xna-cncnet-client#141]
Thanks for your work, so I can start these joyful command & conquer series MOD via your work.
I'm a Mental Omega Player. I encountered some questions and I need your help.
Due to my restricted network condition, nearly every cncnet server access point is unreachable for me, thus I can only connect cncnet via 1 or 2 specific server access point.
But my XNA-client doesn't aware of that situation. So every time opening the cncnet lobby in client means waiting for the server list rolls up and down until the specific server appears, I can see the world-wide server list, but I can't get connected through any of them.
By the way, the tunnel server works normally for me, which I can play the game after its starting, that problem only rises when I try to use cncnet game lobby, when I try to search the game room, and go into them.
Losing connection means a big aftermath, because I must spend a lot of time waiting the server list rolls from the beginning, like "London, UK" (that one is unreachable for me), and "Chicago, IL" (unreachable most of the time for me), then "Newark, NJ", "Santa Ana, CA" (these never reachable for me). That experience likes traveling over the world, looking at so many cities, they are really beautiful cities.
But it's not good for gaming experience.
I tried to find the server-list config file in the MO folder, but I can't find any file like the config file for server list. Only to find a tunnel server list named "tunnel_cache", apparently it's only a cache for tunnel servers, not game lobby servers list.
Another file named "cncnet5.dll", it's a binary file, and I don't think that active game server IP list stored statically in a functioning binary file.
The other files like "gamelobby.ini" are only exterior config files in my sight. I think it is only color and image settings.
I don't know where to set that server IP order list.
I'm not familiar with IRC background workings, even don't know if that server list stores  locally or online. If it's stores online, is there any way to make it work locally with user's configure? Under that situation maybe I can record some IP and write them into the config file statically.
I have a little experience in programming. I can understand easy programming words.
I want your help.
Without your work I can't enjoy the cncnet online gaming. Thanks for your work, again, honestly.

**Comment by pzhlkj6612** [comment]
Hi @Knighthana .
The list of Lobby servers is here:

https://github.com/CnCNet/xna-cncnet-client/blob/f338516fbc176e178c172e0d0f5a373a3cc91af0/DXMainClient/Online/Connection.cs#L28-L49

The program will try to connect to them in order:

https://github.com/CnCNet/xna-cncnet-client/blob/f338516fbc176e178c172e0d0f5a373a3cc91af0/DXMainClient/Online/Connection.cs#L150-L160

Please test the code in PR #142 . I want to know if my modification is effective. Thank you.
