### ISSUE TITLE
Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#15]
Exception has been thrown by the target of an invocation
https://forums.cncnet.org/index.php?topic=6922.0

Log: https://docs.google.com/uc?authuser=0&id=0B8gSFgpT3dl3UFY4dnpOUWZjS0E&export=download

**Comment by Rampastring** [comment]
"Exception has been thrown by the target of an invocation" doesn't tell anything, but you can take a look at the log to see the inner exception that is the actual problem. In this case it was an out-of-bounds array / list access somewhere in the code.

Could use more information on what was going on when it happened.

**Comment by GrantBartlett** [comment]
"The first time it happened right after game end, the second time I believe it randomly happened in game lobby. I try pay attention to it next time when I get it again."

**Comment by GrantBartlett** [comment]
I beleive I've just got this error now.
![error](https://cloud.githubusercontent.com/assets/6104940/21080538/73c39104-bfa9-11e6-9267-bcadee8eed30.png)

[ClientCrashLog_11_12_2016_13_47.txt](https://github.com/CnCNet/xna-cncnet-client/files/644471/ClientCrashLog_11_12_2016_13_47.txt)

**Comment by Rampastring** [comment]
Crashed in CnCNetGameLobby.Channel_UserAdded(object sender, ChannelUserEventArgs e), on

if (Players.Count + AIPlayers.Count > MAX_PLAYER_COUNT)
    AIPlayers.RemoveAt(AIPlayers.Count - 1);

Based on the screenshot and investigating the log, player "mixo" had left the game earlier, but afterwards the game host had still sent a player options message that had "mixo" in it, leading the client to have 8 players in the internal player list. When the new user joined, Players.Count reached 9, which is above the maximum of 8 and caused the client to crash.

**Comment by Rampastring** [comment]
Potentially fixed in https://github.com/CnCNet/xna-cncnet-client/commit/09651803ee1115bddd8754196e0a7ad21a316854

**Comment by Rampastring** [comment]
Assumed fixed. Re-open or create a new issue if something similar is still seen.
