### ISSUE TITLE
YR client Bug and unknown critical problem

### ISSUE THREAD

**Issue by ghost** [CnCNet/xna-cncnet-client#153]
6.9 I downloaded version xna - client added a different channel except #cncnet-yr and entered yr. however, although we use the same localgame and the same version in the game, everyone seems to be an unknown icon. and this is quite annoying. I think this problem is related to client source codes. please solve this bug in the game.

![Screenshot_1](https://user-images.githubusercontent.com/64026619/82724227-e360e780-9cd4-11ea-965a-1c73923b82d5.png)

**Comment by devo1929** [comment]
@Metadorius 
this is due to the change in using /names rather than /whois, that I had mentioned. Not sure if there's much we can do about it right now, given the amount of data that necessitated the change in the first place.
