### ISSUE TITLE
No suitable graphics card found

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#16]
https://forums.cncnet.org/index.php?topic=6936.0

**Comment by Rampastring** [comment]
From the log:

Video controller: SiS Mirage 3 Graphics 

I've never heard of that thing before. Either the user doesn't have drivers installed for it or it doesn't support Shader Model 1.1 and DirectX 9.

**Comment by Rampastring** [comment]
Unsupported graphics chip. There is no way for us to lower the requirement further. This shouldn't be a common issue because Shader Model 1.1 is really old.
