### ISSUE TITLE
Saved game names appear as garbage in Wine

### ISSUE THREAD

**Issue by cdavis5e** [CnCNet/xna-cncnet-client#164]
This code assumes that the title of a saved game in [OLE Compound Document format](https://en.wikipedia.org/wiki/Compound_File_Binary_Format) is always stored at a particular offset:

https://github.com/CnCNet/xna-cncnet-client/blob/421f1b61f42b8a65b2eb847c5a6e30c57962829b/DXMainClient/Domain/SavedGame.cs#L34

This is a very fragile assumption, and it breaks on CDFs produced by Wine. Wine's CDFs, at least on my system, happen to have the title at offset 9c0h. When the client tries to read the Unicode string which it assumes is at 980h, it winds up reading garbage, and the save game names are unreadable in the client. (Saved games in the actual game engine work correctly and display the correct name.)

**Comment by SadPencil** [comment]
Number 2256 is 0x8d0 in hex form, instead of 0x980 in your description above. Maybe you need to double check the offset? You say that the offset is dynamic on various system, is there any document available? And what are `CDFs`?

Besides, this part of codes has been updated with Unicode support. Is the problem still occurs on the latest build of the client on Wine?

**Comment by SadPencil** [comment]
Okay, I got what you said. The problem can be solved. To validate the solution, could you upload a .sav file that is generated from your Wine environment?

```csharp
using OpenMcdf; // installed through Nuget

var cf = new CompoundFile(filename);
var archiveNameBytes = cf.RootStorage.GetStream("Scenario Description").GetData();
var archiveName = Encoding.Unicode.GetString(archiveNameBytes);
Console.WriteLine(archiveName);
```

**Comment by cdavis5e** [comment]
> To validate the solution, could you upload a .sav file that is generated from your Wine environment?

Of course. Here's one from the Mental Omega mission, "Operation: Puppet Master" (Allied 14).
[APUPPET.sav.zip](https://github.com/CnCNet/xna-cncnet-client/files/6013783/APUPPET.sav.zip)

**Comment by SadPencil** [comment]
> 
> 
> > To validate the solution, could you upload a .sav file that is generated from your Wine environment?
> 
> Of course. Here's one from the Mental Omega mission, "Operation: Puppet Master" (Allied 14).
> [APUPPET.sav.zip](https://github.com/CnCNet/xna-cncnet-client/files/6013783/APUPPET.sav.zip)

Yes. It is solved. I'll make a PR for this change.
See the picture below.

![image](https://user-images.githubusercontent.com/11227602/108576558-10702280-7359-11eb-92ae-b983a0cff9d4.png)

If you need, I can seed you the new gaming executable for Mental Omega 3.3.5 that solves this problem.
