### ISSUE TITLE
Can't block users from PM and All Players dialogues

### ISSUE THREAD

**Issue by Martin-Veskilt** [CnCNet/xna-cncnet-client#167]
![image](https://user-images.githubusercontent.com/54605063/88176861-d488a980-cc1f-11ea-93bd-185eed306f22.png)

The right-click context menu option to block players from _Private Messaging_ and _All Players_ dialogue menus does not exist.
It's only present in the main CnCNet lobby, however, due to a recent update removing the display of all players in the main lobby, the block user feature is not helpful for dealing with toxic players.

**Comment by Metadorius** [comment]
Will be closed by #169 once merged.
