### ISSUE TITLE
Potential Map transfers not working

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#17]
Getting a few reports of map transfers not working, in the lobby and now on the forums.

https://forums.cncnet.org/index.php?topic=6928.msg50120#msg50120

**Comment by GrantBartlett** [comment]
Look's to be: https://forums.cncnet.org/index.php?topic=6940.msg50182#msg50182
It transfers fine, but doesn't render the new map? Do you agree?

**Comment by Rampastring** [comment]
To me it looks like the map renderer is started too soon after receiving the new map, basically before the map has been extracted and added to the map list. Since the automatic map renderer is a YR-specific addition, you'll have to debug it yourself.

**Comment by GrantBartlett** [comment]
Yeah makes sense

**Comment by GrantBartlett** [comment]
`05.12. 22:42:03.090    RMP: KIIINGMIIKEY!~4--bqLhaW@gamesurge-83e79170.cable.virginm.net NOTICE #cncnet-yr-game5076648,GO 330;5;10;0;6998a1900641497f1c5aa262a0e349bab0a90a63;Teamgame;972726346,
05.12. 22:42:03.114    Executing callback DoCTCPParsed
05.12. 22:42:03.123    CnCNetGameLobby_CTCPReceived
05.12. 22:42:03.135    MapSharer: Preparing to download map 6998a1900641497f1c5aa262a0e349bab0a90a63
05.12. 22:42:03.142    MapSharer: MapDownloadStarted
05.12. 22:42:03.166    MapSharer: Downloading URL: http://mapdb.cncnet.org/yr/6998a1900641497f1c5aa262a0e349bab0a90a63.zip
05.12. 22:42:03.566    Message received: :lironmen!~4--9YO1tX@gamesurge-71b2e95c.bb.netvision.net.il NOTICE #cncnet-yr-games :GAME R3;3.0.36;8;#cncnet-yr-game9661593;1111111111111111111111;11000;lironmen,Gili,tzach27;[8] Death trap;Battle;46.166.187.82;0

05.12. 22:42:03.574    RMP: lironmen!~4--9YO1tX@gamesurge-71b2e95c.bb.netvision.net.il NOTICE #cncnet-yr-games,GAME R3;3.0.36;8;#cncnet-yr-game9661593;1111111111111111111111;11000;lironmen,Gili,tzach27;[8] Death trap;Battle;46.166.187.82;0,
05.12. 22:42:03.592    Executing callback DoCTCPParsed
05.12. 22:42:03.608    MapSharer: Download of map 6998a1900641497f1c5aa262a0e349bab0a90a63 completed succesfully.
05.12. 22:42:03.619    Executing callback MapSharer_HandleMapDownloadComplete
05.12. 22:42:03.664    Loading custom map Maps\Custom\6998a1900641497f1c5aa262a0e349bab0a90a63.map failed!
05.12. 22:42:03.670    Loading map 6998a1900641497f1c5aa262a0e349bab0a90a63 failed!
05.12. 22:42:03.980    Message received: :Zachiel!~4--IhWhy8@gamesurge-446d4c88.bb.netvision.net.il NOTICE #cncnet-yr-game5076648 :TNLPNG -1

05.12. 22:42:03.990    RMP: Zachiel!~4--IhWhy8@gamesurge-446d4c88.bb.netvision.net.il NOTICE #cncnet-yr-game5076648,TNLPNG -1,
05.12. 22:42:04.025    Executing callback DoCTCPParsed
05.12. 22:42:04.036    CnCNetGameLobby_CTCPReceived
05.12. 22:42:04.511    Message received: :NodMessiah!~4--fU6b5q@gamesurge-1914dddb.gh2.cm.dyn.comporium.net NOTICE #cncnet-yr-games :GAME R3;3.0.36;8;#cncnet-yr-game5807388;NodMessiah's Game;11000;NodMessiah,PureNod;[6] Bay of Pigs;Battle;156.34.174.7;0

05.12. 22:42:04.531    RMP: NodMessiah!~4--fU6b5q@gamesurge-1914dddb.gh2.cm.dyn.comporium.net NOTICE #cncnet-yr-games,GAME R3;3.0.36;8;#cncnet-yr-game5807388;NodMessiah's Game;11000;NodMessiah,PureNod;[6] Bay of Pigs;Battle;156.34.174.7;0,
05.12. 22:42:04.554    Executing callback DoCTCPParsed
05.12. 22:42:04.725    SRM: NOTICE #cncnet-yr-game5076648 :TNLPNG 31
05.12. 22:42:05.259    Message received: :Volannd!~3LVIpuwR4@4e25c1eb.9a1c39ed.8f148421.IP4 JOIN #cncnet

05.12. 22:42:05.275    RMP: Volannd!~3LVIpuwR4@4e25c1eb.9a1c39ed.8f148421.IP4 JOIN #cncnet,
05.12. 22:42:05.289    Executing callback DoUserJoinedChannel
05.12. 22:42:05.537    Message received: :KIIINGMIIKEY!~4--bqLhaW@gamesurge-83e79170.cable.virginm.net NOTICE #cncnet-yr-game5076648 :PO KIIINGMIIKEY;0;1;TheProdigy;0;0;Zachiel;0;0;neo_dev;0;0;

05.12. 22:42:05.546    RMP: KIIINGMIIKEY!~4--bqLhaW@gamesurge-83e79170.cable.virginm.net NOTICE #cncnet-yr-game5076648,PO KIIINGMIIKEY;0;1;TheProdigy;0;0;Zachiel;0;0;neo_dev;0;0;,
05.12. 22:42:05.558    Executing callback DoCTCPParsed
05.12. 22:42:05.574    CnCNetGameLobby_CTCPReceived
05.12. 22:42:06.340    Message received: :|NC|-Lautaa!~1ARIBWRS9@lauta.user.gamesurge QUIT :Quit: 1.31 r16 0

05.12. 22:42:06.353    RMP: |NC|-Lautaa!~1ARIBWRS9@lauta.user.gamesurge QUIT Quit: 1.31 r16 0,
05.12. 22:42:06.379    Executing callback DoUserQuitIRC
05.12. 22:42:07.240    SRM: NOTICE #cncnet-yr-game5076648 :MAPFAIL 6998a1900641497f1c5aa262a0e349bab0a90a63
05.12. 22:42:08.043    Message received: :KIIINGMIIKEY!~4--bqLhaW@gamesurge-83e79170.cable.virginm.net NOTICE #cncnet-yr-game5076648 :GO 330;5;10;0;b0f4f3ee414a1faec5c6cbb378fae91cce7093ec;Teamgame;972726346

05.12. 22:42:08.069    RMP: KIIINGMIIKEY!~4--bqLhaW@gamesurge-83e79170.cable.virginm.net NOTICE #cncnet-yr-game5076648,GO 330;5;10;0;b0f4f3ee414a1faec5c6cbb378fae91cce7093ec;Teamgame;972726346,
05.12. 22:42:08.091    Executing callback DoCTCPParsed
05.12. 22:42:08.103    CnCNetGameLobby_CTCPReceived
05.12. 22:42:08.115    MapSharer: Preparing to download map b0f4f3ee414a1faec5c6cbb378fae91cce7093ec
05.12. 22:42:08.134    MapSharer: MapDownloadStarted
05.12. 22:42:08.151    Message received: :payramid___!~4--DwHr1T@d53feb97.932df72e.94e78555.IP4 NOTICE #cncnet-yr-games :GAME R3;3.0.36;6;#cncnet-yr-game2507778;sedona ffa;10000;payramid___,Balrog17,Skippy92;[6] Sedona Pass;Battle;46.166.187.82;0

05.12. 22:42:08.168    RMP: payramid___!~4--DwHr1T@d53feb97.932df72e.94e78555.IP4 NOTICE #cncnet-yr-games,GAME R3;3.0.36;6;#cncnet-yr-game2507778;sedona ffa;10000;payramid___,Balrog17,Skippy92;[6] Sedona Pass;Battle;46.166.187.82;0,
05.12. 22:42:08.176    MapSharer: Downloading URL: http://mapdb.cncnet.org/yr/b0f4f3ee414a1faec5c6cbb378fae91cce7093ec.zip
05.12. 22:42:08.193    Executing callback DoCTCPParsed
05.12. 22:42:08.258    MapSharer: Download of map b0f4f3ee414a1faec5c6cbb378fae91cce7093ecfailed! Reason: The remote server returned an error: (404) Not Found.`

**Comment by GrantBartlett** [comment]
Points to note here:

- 05.12. 22:42:03.670 Loading map 6998a1900641497f1c5aa262a0e349bab0a90a63 failed!

But also, when the host changed the map, it couldn't download. 
- MapSharer: Download of map b0f4f3ee414a1faec5c6cbb378fae91cce7093ecfailed! Reason: The remote server returned an error: (404) Not Found.`

**Comment by GrantBartlett** [comment]
Think I've found the issue but still needs looking into tomorrow.  Map renderer I believe, is continuously running, which may explain why the map can't be accessed when it gets downloaded, renderer catches it and renders it instead.

**Comment by Rampastring** [comment]
No, there's no specific way of starting and handling threads. Usually there's only 2 threads running, the main thread / UI thread and the thread that's responsible for receiving messages from the CnCNet IRC server. Temporary additional threads are also spawned by the updater and on client startup (one thread initializes the updater while another loads maps, this lowers the startup time by a few hundred milliseconds), but they're stopped as soon as they've finished their tasks.

**Comment by GrantBartlett** [comment]
Thanks makes sense.

It was failing on this line. https://github.com/CnCNet/xna-cncnet-client/blob/master/DXMainClient/Domain/Multiplayer/Map.cs#L296

Try/catched it for now and that's fixed the bug that was transfers. Wanted to ask what the purpose of that was for, maybe a DTA specific thing?

**Comment by Rampastring** [comment]
That's supposed to make it try to load the map preview from the same directory where the custom map resides, with the same filename except for changing the .map to .png.

**Comment by Rampastring** [comment]
@GrantBartlett Check if it works without try-catch after this commit:
https://github.com/CnCNet/xna-cncnet-client/commit/f319f052a2bc424e82415a04e762d5d7be162e0d

**Comment by Rampastring** [comment]
Confirmed to work.
