### ISSUE TITLE
Loader hangs on startup

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#18]
![3](https://cloud.githubusercontent.com/assets/6104940/20918344/6eb83526-bb8e-11e6-8518-81de436bbcc1.png)

https://forums.cncnet.org/index.php?topic=6934.0

**Comment by Rampastring** [comment]
Based on the logfile it has taken almost 2 minutes to load custom maps.

**Comment by Rampastring** [comment]
I pushed a couple of commits that improve the loading of custom maps. If the issue is still present, then they probably just have tons of custom maps and will have to deal with long loading times or remove some of them.

**Comment by Rampastring** [comment]
I pushed another update that makes loading custom maps faster.
