### ISSUE TITLE
Client crash with message box

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#19]
"If you click to the left on the message box when you have a bunch of characters typed in, crashes the client."
https://www.dropbox.com/s/wo4dpirbkdh1frm/client.log?dl=0

**Comment by Rampastring** [comment]
Fixed with https://github.com/CnCNet/xna-cncnet-client/commit/d93ed9474286d2038a1a874175ef591420eebdbd
