### ISSUE TITLE
An unexpected error has occurred. Source: Microsoft.Xna.Framework.Graphics

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#2]
Upon startup https://forums.cncnet.org/index.php?topic=6861.msg49900#msg49900

**Comment by Rampastring** [comment]
No idea about this one. The log says this:

Hardware info: Intel Pentium III Xeon processor (2 cores)  Video controller: Radeon X1300/X1550 Series 

The GPU should be enough, but the CPU is pretty ancient.

**Comment by Rampastring** [comment]
The user only has Service Pack 2 installed for Windows XP, and refuses to install Service Pack 3.
