### ISSUE TITLE
Updater fails on Linux

### ISSUE THREAD

**Issue by Metadorius** [CnCNet/xna-cncnet-client#203]
Has to do with hardcoded backslash paths and probably `.dat` extension of a second-stage updater.
![image](https://user-images.githubusercontent.com/17500545/100084760-d5db1480-2e53-11eb-8f6b-a3673e344fa9.png)

**Comment by SadPencil** [comment]
C#: use `Path.DirectorySeparatorChar` to replace the backslash in the path.

**Comment by Metadorius** [comment]
Fixed in 771762.
