### ISSUE TITLE
Add .editorconfig file for coding style

### ISSUE THREAD

**Issue by SadPencil** [CnCNet/xna-cncnet-client#214]
Just as what @frg2089 said, an [.editorconfig](https://aka.ms/editorconfigdocs) file is needed to customize the coding style of this project.

For example, the "var-or-typename" style can be defined at the `.editorconfig` file as below:
```ini
[*.cs]
# var preferences
csharp_style_var_for_built_in_types = false:suggestion
csharp_style_var_when_type_is_apparent = false:suggestion
csharp_style_var_elsewhere = true:suggestion
```

An example of `.editorconfig` file can be obtained by creating a new `.editorconfig` file (.NET) in Visual Studio.

**Comment by Woodykaixa** [comment]
Agree. Since the coding style seems different with reshaper, and I'm considering to add some features.
