### ISSUE TITLE
Unable to load DLL 'Mfplat.dll'

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#22]
https://forums.cncnet.org/index.php?topic=6970.0

![cncnet error](https://cloud.githubusercontent.com/assets/6104940/21023017/a8504d34-bd76-11e6-992f-2f638167ddaa.png)

08.12. 17:37:24.394    Source: MonoGame.Framework
08.12. 17:37:24.394    TargetSite.Name: get_State
08.12. 17:37:24.394    Stacktrace:    ved Microsoft.Xna.Framework.Media.MediaPlayer.get_State()
   ved ‮‭‮‎⁮⁮⁭​‎‍‭‍⁬‮‪⁯‫‫⁭​‫⁪‎​⁫‍‏⁭⁫​⁯⁭‫‪‬‬‪⁭‏⁪‮.⁫⁫‌‌‎⁭‭‫⁮​⁬​​​‮⁬‫⁯‮⁪⁫‬‮‮⁭​‎⁬‪⁫‎⁭‪‎‭⁭⁭⁯‮‫‮()
   ved ‮‭‮‎⁮⁮⁭​‎‍‭‍⁬‮‪⁯‫‫⁭​‫⁪‎​⁫‍‏⁭⁫​⁯⁭‫‪‬‬‪⁭‏⁪‮.⁬‏⁪‍‎‪​‌⁫‭‍‪⁭⁫‌⁬⁪‌​‍‬‏‫⁫‫⁭⁬⁮‪⁫‎‮‌⁮‍‌⁮‌⁪‍‮()
   ved ​‪⁪⁭⁭⁬⁬⁭‫⁯‬⁬​​⁬‭‎‌‍​⁯‏⁪‫‪⁯⁪‭⁬‮‏‍‎‫⁪⁪‌​‎⁮‮.⁫‍‏⁮‭‍‌⁬‎‫‮⁮‫‭‪⁭‏⁮‪⁬‎⁯⁫⁭‏⁪‬​⁮‭‏‫⁫‭‎‍‭‏‏⁬‮(Object , EventArgs )
   ved ‮‭‮‎⁮⁮⁭​‎‍‭‍⁬‮‪⁯‫‫⁭​‫⁪‎​⁫‍‏⁭⁫​⁯⁭‫‪‬‬‪⁭‏⁪‮.⁪‎‎⁪‫‮‎‌‍⁫‎​⁯‮⁪⁭‫‌⁯​‍‌​​⁮⁪⁫⁪⁯‬‪⁭‎‮‬‫⁫‬‍⁮‮(Object , EventArgs )
   ved Rampastring.XNAUI.XNAControls.XNAControl.OnLeftClick()
   ved Rampastring.XNAUI.XNAControls.XNAButton.OnLeftClick()
   ved Rampastring.XNAUI.XNAControls.XNAControl.Update(GameTime gameTime)
   ved Rampastring.XNAUI.XNAControls.XNAButton.Update(GameTime gameTime)
   ved Rampastring.XNAUI.XNAControls.XNAControl.Update(GameTime gameTime)
   ved Rampastring.XNAUI.XNAControls.XNAPanel.Update(GameTime gameTime)
   ved ‮‭‮‎⁮⁮⁭​‎‍‭‍⁬‮‪⁯‫‫⁭​‫⁪‎​⁫‍‏⁭⁫​⁯⁭‫‪‬‬‪⁭‏⁪‮.‏‫⁭‫⁬‍⁪‮‭⁫‌​‮⁬‭⁬⁭​​⁪‌‎‭‫⁮⁮‬⁫‎‮‭‏⁪‬‍​‍‪‪‫‮(GameTime )
   ved Rampastring.XNAUI.WindowManager.Update(GameTime gameTime)
   ved Microsoft.Xna.Framework.Game.<>c.<.cctor>b__114_1(IUpdateable updateable, GameTime gameTime)
   ved Microsoft.Xna.Framework.Game.SortingFilteringCollection`1.ForEachFilteredItem[TUserData](Action`2 action, TUserData userData)
   ved Microsoft.Xna.Framework.Game.Update(GameTime gameTime)
   ved Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   ved Microsoft.Xna.Framework.Game.Tick()
   ved MonoGame.Framework.WinFormsGameWindow.RunLoop()
   ved MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   ved Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   ved Microsoft.Xna.Framework.Game.Run()
   ved ‏⁭‬⁪⁪‍‭‪⁬‎‫⁯⁪⁭‬‎‎‮⁮⁮‌‫‌⁮⁮⁮‪‬‏⁮⁫​‎‪‭‏‎⁯‎‬‮.‫‪‭‭‏‪​‭⁯‍⁪‭‌‍⁪‬​‌‎‮⁪⁭‭⁮​‌‍‍‭‫‬⁯‬⁭‭⁭‪‬‌⁯‮()
   ved ⁬‪‪⁬⁭⁫⁪‎⁬⁯⁪⁭⁭‮‮‮⁪‮‌‬‬​‏‫‪⁪​‭⁫⁮⁫‎‌⁪‮‮‍‍⁫‏‮.‎⁪‪⁫‬‭‮⁯⁬⁪⁪⁪‎‬‏⁮‪‮‪‮‏‏‮⁯‌‪‮‎‎‮‪‮⁯​‮⁫⁪⁮⁪‫‮(String[] )
   ved ⁬⁬⁮⁭‮‍‭‍⁯‏‎⁫‎‮⁯⁪‬​⁯‏‭‮⁪‪‭​‭⁭⁬‌‎‬‭‌​‬⁮‫‌⁯‮.‮‏‏⁭⁬⁯⁪‎​‏⁬⁬⁬‭⁮‬‭‭‎‌⁮‍⁭⁯⁯⁫⁪‫​‭⁬⁫‪‏⁫‎‌⁪⁪⁯‮(String[] )
08.12. 17:37:24.394    InnerException info:
08.12. 17:37:24.394    Message: Unable to load DLL 'Mfplat.dll': Den angitte modulen ble ikke funnet. (Exception from HRESULT: 0x8007007E)
08.12. 17:37:24.394    Stacktrace:    ved SharpDX.MediaFoundation.MediaFactory.MFStartup_(Int32 arg0, Int32 arg1)
   ved SharpDX.MediaFoundation.MediaFactory.Startup(Int32 version, Int32 dwFlags)
   ved SharpDX.MediaFoundation.MediaManager.Startup(Boolean useLightVersion)
   ved Microsoft.Xna.Framework.Media.MediaManagerState.CheckStartup()
   ved Microsoft.Xna.Framework.Media.MediaPlayer.PlatformInitialize()
   ved Microsoft.Xna.Framework.Media.MediaPlayer..cctor()
08.12. 17:37:28.175    Map Rendering: 403 / 635
08.12. 17:37:28.175    Starting map generator.

**Comment by Rampastring** [comment]
MLPlat.dll is apparently missing on some editions of Windows. It's included with the Media Feature Platform, downloadable from the following links (depending on Windows version):

Windows 8 N/KN - http://www.microsoft.com/en-us/download/details.aspx?id=30685
Windows 8.1 N/KN - http://www.microsoft.com/en-us/download/details.aspx?id=40744
Windows 8.1 N/KN Update - http://www.microsoft.com/en-us/download/details.aspx?id=42503
Windows 10 N/KN - https://www.microsoft.com/en-us/download/details.aspx?id=48231
Windows 10 N/KN Update 1511 - https://www.microsoft.com/en-US/download/details.aspx?id=49919
Windows 10 N/KN Update 1607 - https://www.microsoft.com/en-us/download/details.aspx?id=53356
