### ISSUE TITLE
Add missing game options to TS client

### ISSUE THREAD

**Issue by PTapioK** [CnCNet/xna-cncnet-client#223]
Compared to funky's client, we are missing following options:
* Aimable Sams
* Shared Control
* Attack Neutral Units
* Fog Of War (this is not probably worth adding if it doesn't work) 
* Bases (It is uncertain how this option actually works, or is it same as having Short Game enabled. How about Bases On + Short Game Off?)
* Multiple Factory

Funky's client
![funky_client](https://user-images.githubusercontent.com/1269683/116586214-e2432c00-a921-11eb-9462-dfb2c9c16606.PNG)

Rampa's client
![rampa_client](https://user-images.githubusercontent.com/1269683/116586227-e4a58600-a921-11eb-9acf-1a3cd5881663.PNG)

**Comment by Metadorius** [comment]
This should be transferred to TS client repo now that it's up.
