### ISSUE TITLE
i tried launching MO on wine in Exagear and i got this error message

### ISSUE THREAD

**Issue by XrazorXGaming** [CnCNet/xna-cncnet-client#230]
i've done every procedure and steps on how to launch MO here and i got this error on exagear
![Screenshot_20210619-010148](https://user-images.githubusercontent.com/57312306/122590143-ac344580-d050-11eb-88d0-5cd073a33c67.png)

**Comment by Rampastring** [comment]
As the error message hints, you need to install Microsoft XNA Framework 4.0 Refresh Redist: https://www.microsoft.com/en-us/download/details.aspx?id=27598

**Comment by deftdawg** [comment]
Can use winetricks to install it `winetricks xna40` ... From what I've read elsewhere you'll also have to remove *.wav and *.xnb files to get the app to start, though I haven't managed it yet.
