### ISSUE TITLE
No maps in the map list

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#24]
https://forums.cncnet.org/index.php?topic=6982.0

09.12. 21:22:25.418    Loading maps.
09.12. 21:22:25.418    Loading multiplayer map list failed!!!.

I'm also getting the log off someone else who has this same issue in the lobby.

**Comment by GrantBartlett** [comment]
https://forums.cncnet.org/index.php?topic=6983.0;topicseen

**Comment by Rampastring** [comment]
Happens when MPMaps.ini either does not exist or does not have the [MultiMaps] section in it. Make sure that you're including all necessary files with CnCNet YR.

**Comment by GrantBartlett** [comment]
You're right the new installer placed it in the wrong directory. The guy's MPMaps.ini does not exist. 

Thanks!

**Comment by GrantBartlett** [comment]
Hold the phone, 

MPMapsPath=INI\MPMaps.ini does exist
And so does [MultiMaps]

**Comment by Rampastring** [comment]
Is the MPMaps.ini in the INI\ directory then?
