### ISSUE TITLE
Joining another game remembers host options

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#25]
When you join X game, you inherit the host options of that game. So when you go to create your own game, those options are also applied. 

Not sure what you want to do with this, if it is intentional or not.

Original post: https://forums.cncnet.org/index.php?topic=7000.0

**Comment by Rampastring** [comment]
It's because of an oversight. I intentionally made it so that when you're hosting a game, and then exit it and then host another game, the settings from your previous game are remembered. I didn't think of this use case (joining and leaving another host's game before hosting your own) when I coded it so.

If this behaviour is considered unwanted, I'll make the client apply default settings for non-host players when they exit a game.

**Comment by GrantBartlett** [comment]
https://forums.cncnet.org/index.php?topic=7064.0

This is possibly causing issues, though not really sure. I may need you to investigate what's going on with this?

**Comment by Rampastring** [comment]
I doubt it's this feature that'd cause the issue. Looks more likely that the client is either not sending a proper game options message, or a bad game options message is sent, or a game options message is parsed incorrectly.

Ra2Nub also claims that it didn't happen in the first release of this client. If that's the case, make sure that you haven't modified the game options broadcasting stuff in YR.

I also haven't seen or heard this happening in DTA, TI or MO. Actual steps to reproduce would be helpful.

**Comment by GrantBartlett** [comment]
https://forums.cncnet.org/index.php?topic=7064.msg50866#msg50866

Nothing is modified in the game options broadcasting. 

You can see the map selected there is brought over from the game he joined. The map that's shown, is not the Alamo yet it's selected.

**Comment by GrantBartlett** [comment]
In addition, we could add a check before the game starts perhaps on spawnmap.ini to check the  SHA1 files of each user matches against the hosts? If it doesn't, something's not right.

**Comment by Rampastring** [comment]
When a game options message (that contains the map) is received from the game host, the map is changed but the map list box and game mode dropdown aren't updated. It doesn't have anything to do with the map getting potentially out of sync.

**Comment by GrantBartlett** [comment]
https://forums.cncnet.org/index.php?topic=7064.msg50972#msg50972

**Comment by Rampastring** [comment]
Nope, haven't been able to take a look at the logs yet.

**Comment by GrantBartlett** [comment]
Any chance you could look into it this weekend please? Or somewhat soon. I want to try and push a new update on Sunday if I can. This broken game state is becoming annoying.

**Comment by Rampastring** [comment]
I took a peek at the logs a few days ago and couldn't spot a clear cause. It'd be best if you managed to reproduce it in a debugging environment so you could take a look at what's going on with the current map and game mode when the bug happens.

My current school schedule is pretty intense, I don't think I'm going to have a free weekend in a couple of months.

**Comment by GrantBartlett** [comment]
@Rampastring think I've narrowed down the issue. 

1. Player A has joined a game with a bugged map. Left the game. Player A creates their own game.
2. Player A selects what they think is a normal map. The map is an official map like Heck Freezes Over.
3. Player B joins Player A's game. The map is not found yet it being official. Player B downloads the map, and thinks nothing more of it.
4. Player B has just been infected with this bugged state.

If Player B now goes to create a game, and selects another official standard map like Country Swing, he will initiate this bugged state to someone else who joins their game.

**The problem:**
When Player B makes a new game, and select a standard map, the game mode is incorrect. The game mode should infact be of Game mode: Battle. Yet it's inherrited the previous game mode of "Standard". 
Player C then joins Player B's game and downloads this map because the Game Mode is wrong.

**Comment by Rampastring** [comment]
Interesting. Nice detailed analysis. I'll look at it when I can.

**Comment by Rampastring** [comment]
@GrantBartlett Check if the commit referenced above helps.

**Comment by GrantBartlett** [comment]
@Rampastring Thanks for looking into it, from initial testing it updates the game correctly now when a player gets into that state. I'll give it some further testing (I've also pushed it live for some feedback)

**Comment by Rampastring** [comment]
I think we can assume this one fixed after 2 years of no error reports.
