### ISSUE TITLE
Mac Os X El Capitan & Crossover support

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#26]
Awaiting log details. I will also try and test and see if it can work on Crossover for Mac.

https://forums.cncnet.org/index.php?topic=6980.0

**Comment by Rampastring** [comment]
Running the WindowsGL build of the client will probably be a lot easier.

**Comment by Rampastring** [comment]
Labeling this as an enhancement because the original scope of the project was Windows only, but getting it to run on Macs and Linux-based OSs would be nice.

**Comment by Rampastring** [comment]
With the fix for issue #30, Crossover should be able to run the client without need for the user to delete / rename the main menu music files.
