### ISSUE TITLE
LAN game instant crash upon joining lobby

### ISSUE THREAD

**Issue by dwginger** [CnCNet/xna-cncnet-client#273]
![Untitled](https://user-images.githubusercontent.com/13887318/145305176-4a7d88dc-3c55-4616-a6e8-8afaaae1182a.png)

**Comment by devo1929** [comment]
@dwginger this has officially been resolved and included in v8.8.1.

**Comment by dwginger** [comment]
> 

Just tested it after applying the update 8.8.1, works now.
Thank you
