### ISSUE TITLE
Message: Text contains characters that cannot be resolved by this SpriteFont.

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#3]
"The problem occurs when I scroll over the games list. Some error called spirite or something"

https://forums.cncnet.org/index.php?topic=6874.msg49902#msg49902

**Comment by GrantBartlett** [comment]
Second more detailed report: 

An error occurs every time after few seconds i have joined in lobby.

Upd: To be more exact, error occurs when i scroll over game list, and when i select a certain game which probably has a map with a name with an "unknown character". I think here is the same issue: https://forums.cncnet.org/index.php?topic=6874.0

![ss_109](https://cloud.githubusercontent.com/assets/6104940/20858273/32f0ecbe-b93a-11e6-84e2-f321f26d5dae.PNG)

**Comment by Rampastring** [comment]
Update the SpriteFonts in the Resources to the latest version that are included in the repository.

**Comment by Rampastring** [comment]
This should also fix it: https://github.com/CnCNet/xna-cncnet-client/commit/c5d0c8081e38b1c7dff8a5c5a999654e782d4380

But you should still update the sprite fonts in YR.
