### ISSUE TITLE
Ignoring CTCP game message because of an invalid amount of parameters.

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#32]
Is this because of some sort of encoding? There are black question marks in the log file if you see below.
Full log: https://drive.google.com/file/d/0B8gSFgpT3dl3d3g4MERFR2J6T0U/view
Inspected from this this post: https://forums.cncnet.org/index.php?topic=7064.msg50972#msg50972

27.12. 20:26:36.490    Executing callback ⁯‪​‍‮‮⁭‪‎⁬⁯‮‪‌‍⁮‏⁮‍⁪‎‫⁮‌‭⁪‬‏‮‎‏‍‪⁫⁬⁪‫⁬⁪⁯‮
27.12. 20:26:36.492    Executing callback ⁯‪​‍‮‮⁭‪‎⁬⁯‮‪‌‍⁮‏⁮‍⁪‎‫⁮‌‭⁪‬‏‮‎‏‍‪⁫⁬⁪‫⁬⁪⁯‮
27.12. 20:26:36.493    Executing callback ⁯‪​‍‮‮⁭‪‎⁬⁯‮‪‌‍⁮‏⁮‍⁪‎‫⁮‌‭⁪‬‏‮‎‏‍‪⁫⁬⁪‫⁬⁪⁯‮
27.12. 20:26:36.495    RMP: Robertm67!~4--xdlsAr@gamesurge-2ef15ddf.cable.virginm.net NOTICE #cncnet-yr-games, GAME R3;3.0.47;8;#cncnet-yr-game8602389;Robertm67's Game;10000;Robertm67;[6] Sedona Pass;Battle;46.166.187.82;0 ,
27.12. 20:26:36.496    RMP: BuBy!~4--M9qbWB@af2fb022.cec8ed71.26020826.IP4 NOTICE #cncnet-yr-games, GAME R3;3.0.47;8;#cncnet-yr-game3221733;BuBy's Game;11000;BuBy,USER;[8] Irvine, California;Free For All;27.254.64.37;0 ,
27.12. 20:26:36.499    RMP: ColdRage_!~1IEUTkSNA@f818e96c.b3f3dae3.6ed5beb3.IP4 JOIN #cncnet,
27.12. 20:26:36.500    RMP: AndrewGamer!~4--eLScgU@c8eebea2.c9badb68.40f1b621.IP4 NOTICE #cncnet-yr-games, GAME R2;N/A;8;#cncnet_YR-game678760;AndrewGamer's Game;00000;AndrewGamer,Jorik220,;����  2 - 5. ���� + ����� ��������;Standard;1; ,
27.12. 20:26:36.503    RMP: RNLAF!~4--QavYjS@gamesurge-445300eb.cm-3-2b.dynamic.ziggo.nl NOTICE #cncnet-yr-games, GAME R3;3.0.47;8;#cncnet-yr-game7828528;Pestventjes;01000;RNLAF,TurboTYNO,ivar;[8] Heck Freezes Over;Megawealth;62.141.38.182;0 ,
27.12. 20:26:36.510    Executing callback ⁬‌‌‍⁭​‫‫‌‮‬‭‏⁫‭‬‎‫‫‏⁫‫‬⁫‍‭‍‌⁫‫‏‎⁬‮⁮⁮⁯‏‮‍‮
27.12. 20:26:36.512    Executing callback ⁬‌‌‍⁭​‫‫‌‮‬‭‏⁫‭‬‎‫‫‏⁫‫‬⁫‍‭‍‌⁫‫‏‎⁬‮⁮⁮⁯‏‮‍‮
27.12. 20:26:36.513    Executing callback ​‪⁮‫‪⁭⁯‭‌‍⁬⁫‮⁯‍⁫‭‎‭‮‮‍‬​‬‎‌‎‮‌‌‪‮‏‪⁪‍⁮‮‮
27.12. 20:26:36.521    Executing callback ⁬‌‌‍⁭​‫‫‌‮‬‭‏⁫‭‬‎‫‫‏⁫‫‬⁫‍‭‍‌⁫‫‏‎⁬‮⁮⁮⁯‏‮‍‮
27.12. 20:26:36.522    Ignoring CTCP game message because of an invalid amount of parameters.
27.12. 20:26:36.525    Executing callback ⁬‌‌‍⁭​‫‫‌‮‬‭‏⁫‭‬‎‫‫‏⁫‫‬⁫‍‭‍‌⁫‫‏‎⁬

**Comment by Rampastring** [comment]
The black question marks seem to be odd characters in the map name.

The reason for the message is that someone hosted a game using the previous (in CnCNet YR terms, version 2.x) client.
