### ISSUE TITLE
Cursor

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#33]
There's a report of playing a game, finishing and then it appears in the client along with cursor.cur from Resources.

https://forums.cncnet.org/index.php?topic=7139.0;topicseen
![cursor](https://cloud.githubusercontent.com/assets/6104940/21659428/8ddd3e88-d2c2-11e6-98c3-91b9fcfda828.png)

Screenshot above shows YR's in game cursor, but the printscreen doesn't show that both cursors show up.
The cursor in Resources directory is just the default windows cursor that windows uses.

**Comment by Rampastring** [comment]
https://github.com/CnCNet/xna-cncnet-client/commit/c622f88d198f57d35e0004fb90fd32226f0a4afd
