### ISSUE TITLE
White Screen upon loadup

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#34]
![client](https://cloud.githubusercontent.com/assets/6104940/21957739/bb24339e-da95-11e6-84b1-ea1e1a0385c4.png)
[client.txt](https://github.com/CnCNet/xna-cncnet-client/files/706189/client.txt)

Log indicates nothing wrong? https://forums.cncnet.org/index.php?topic=7195.0;topicseen

**Comment by Rampastring** [comment]
Graphics card or graphics driver issue.

If they have a laptop with an integrated Intel GPU and a discrete Nvidia GPU, they could try running the client on the other GPU instead of what's set as default.

**Comment by Rampastring** [comment]
Another thing to try is installing XNA Framework Redistributable 4.0 Refresh from https://www.microsoft.com/en-us/download/details.aspx?id=27598 and then running Resources\clientxna.exe instead of CnCNetYRLauncher.exe.
