### ISSUE TITLE
Potential ultra wide crash - 5120x1440 

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#359]
Is it possible the client is crashing out on ultra wide resolution or was this something unrelated? 

Looks like they sovled it by doing the following:

> - Edit .INI file to use 2560x1440
> - Manually resize the monitor to 2560x1440> - Edit .INI file to use 2560x1440
> - Manually resize the monitor to 2560x1440

Log file from this support topic: https://forums.cncnet.org/topic/12344-crash-when-installing-and-attempting-to-run-the-first-time/

```
15.08. 02:37:58.220    ***Logfile for Yuri's Revenge client***
15.08. 02:37:58.223    Client version: 2.8.0.0
15.08. 02:37:58.224    Loading settings.
15.08. 02:37:58.231    Failed to load the translation file. Could not find file 'C:\Program Files\EA Games\Command and Conquer Red Alert II\Resources\Translation.ini'.
15.08. 02:37:58.455    Initializing updater.
15.08. 02:37:58.521    Update mirror count: 1
15.08. 02:37:58.521    Running from: clientdx.exe
15.08. 02:37:58.523    Operating system: Microsoft Windows NT 6.2.9200.0
15.08. 02:37:58.523    Selected OS profile: WIN810
15.08. 02:37:58.523    Current culture: en-US
15.08. 02:37:58.525    Removing partial custom component downloads.
15.08. 02:37:58.526    Checking for the existence of FinalSun.ini.
15.08. 02:37:58.527    FinalSun.ini doesn't exist - writing default settings.
15.08. 02:37:58.527    An exception occured while checking the existence of FinalSun settings
15.08. 02:37:58.528    Writing installation path to the Windows registry.
15.08. 02:37:58.532    Starting background processing of INI files.
15.08. 02:37:58.532    /INI/Base does not exist, skipping background processing of INI files.
15.08. 02:37:59.301    Initializing GameClass.
15.08. 02:37:59.436    InitGraphicsMode: 5120x1440
15.08. 02:37:59.444    KABOOOOOOM!!! Info:
15.08. 02:37:59.445    Message: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

15.08. 02:37:59.446    Source: SharpDX
15.08. 02:37:59.446    TargetSite.Name: CheckError
15.08. 02:37:59.446    Stacktrace:    at SharpDX.Result.CheckError()
   at SharpDX.DXGI.SwapChain.ResizeBuffers(Int32 bufferCount, Int32 width, Int32 height, Format newFormat, SwapChainFlags swapChainFlags)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.CreateSizeDependentResources()
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset()
   at Rampastring.XNAUI.WindowManager.InitGraphicsMode(Int32 iWidth, Int32 iHeight, Boolean bFullScreen)
   at DTAClient.DXGUI.GameClass.SetGraphicsMode(WindowManager wm)
   at DTAClient.DXGUI.GameClass.Initialize()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at DTAClient.Startup.Execute()
   at DTAClient.PreStartup.Initialize(StartupParams parameters)
   at DTAClient.Program.Main(String[] args)

```

**Comment by metaldrummer610** [comment]
Just following up on this. I'm getting the same crash on my machine with an ultrawide monitor that's 5120x1440. Following @GrantBartlett's link to the forum post, if I changed my monitor settings to 2560x1440 temporarily, I can actually launch the CNCNet client. I changed the client to run in windowed mode and kept it at 2560x1440, then changed my monitor back to 5120x1440 and relaunched the client. Everything worked like it was supposed to.

**Comment by SadPencil** [comment]
PR 555 is trying to fix this but we need a tester with an ultra-wide monitor

**Comment by SadPencil** [comment]
> Just following up on this. I'm getting the same crash on my machine with an ultrawide monitor that's 5120x1440. Following @GrantBartlett's link to the forum post, if I changed my monitor settings to 2560x1440 temporarily, I can actually launch the CNCNet client. I changed the client to run in windowed mode and kept it at 2560x1440, then changed my monitor back to 5120x1440 and relaunched the client. Everything worked like it was supposed to.

We have a potential fix right now. Do you want to volunteer testing it?

**Comment by metaldrummer610** [comment]
I would love to, but I actually returned that monitor because it was making me motion sick while playing certain games. The closest I have is a 34" widescreen that's 3440x1440. I haven't tried it on that monitor before, but if it does crash on there, I'd be happy to test the fix.

**Comment by SadPencil** [comment]
> I would love to, but I actually returned that monitor because it was making me motion sick while playing certain games. The closest I have is a 34" widescreen that's 3440x1440. I haven't tried it on that monitor before, but if it does crash on there, I'd be happy to test the fix.

Thanks for the reply. According to our analysis, this issue will only happen if either width or height exceeds ~4000 pixels. So a 3440x1440 monitor should not cause a crash.

**Comment by metaldrummer610** [comment]
Ah, man! Alright, well it was worth a try! I hope someone with a large monitor comes around to try test it then. Good luck with it!

**Comment by SadPencil** [comment]
> Ah, man! Alright, well it was worth a try! I hope someone with a large monitor comes around to try test it then. Good luck with it!

If you are interested in participating the test:

1. Download and install this mod: https://projectphantom.net/download/
2. Go to https://github.com/CnCNet/xna-cncnet-client/pull/555#issuecomment-2335351236 and download "artifacts-Ares.zip" file
3. Extract and override the Resources folder. Note that files such as clientdx.exe and ClientGUI.dll etc should be overwritten during this step.
4. Run the client and test whether it works well by switching client resolutions as well as togging full screen modes.

Based on your monitor resolution, it should most likely work well.
