### ISSUE TITLE
Generate OnlineId cross-platform implementation

### ISSUE THREAD

**Issue by Rans4ckeR** [CnCNet/xna-cncnet-client#375]
Follow up of:
- https://github.com/CnCNet/xna-cncnet-client/pull/341

> - Windows specific functionality currently disabled on other platforms:
>   - Generate OnlineId (Startup)
>     - Registry (Microsoft.Win32)
>     - SecurityIdentifier (System.Security.Principal.Windows)
>     - WMI (System.Management)

A cross-platform version for Generate OnlineId needs to be implemented.

**Comment by SadPencil** [comment]
/var/lib/dbus/machine-id and /etc/machine-id (systemd based) on Linux
