### ISSUE TITLE
Hiding certain factions for certain checkboxes

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#38]
Hi - I would like to know the best approach about handling hiding certain factions based on a checkbox.
In this case if an RA2 Mode checkbox was checked, what would be the best way to hiding an faction?

Thanks

**Comment by Rampastring** [comment]
I don't think hiding the factions is a good idea, but you should gray them out instead. This prevents players from picking the factions.

When a game option is changed and the game options are applied, check if any of the players have an invalid side picked. If they do, revert them to Random. This https://github.com/CnCNet/xna-cncnet-client/blob/master/DXMainClient/DXGUI/Multiplayer/GameLobby/GameLobbyBase.cs#L336 could be a good function for it, check the function in the derived classes (MultiplayerGameLobby, CnCNetGameLobby, LANGameLobby, SkirmishLobby) as well. The same function also works for disabling / enabling the factions, at least for the game host. I think if done properly, it should work for non-host players as well.

**Comment by GrantBartlett** [comment]
Great, look forward to looking into this now that I have an idea, thanks for the pointers!

**Comment by Rampastring** [comment]
You're welcome. If you need more help or pointers, feel free to ask :)

**Comment by GrantBartlett** [comment]
![disabledfaction](https://cloud.githubusercontent.com/assets/6104940/22486074/f7b9eb1a-e7ff-11e6-97e6-0efd949a08de.png)

Had a quick look for a few mins and got the OnGameOptionsChanged call and looped through the checkboxes to see if Ra2Mode was checked. Did the trick.

Will look at the next bits soon (Random faction, changing players existing sides - including host), thanks again

**Comment by GrantBartlett** [comment]
Perfect did the trick thanks!
