### ISSUE TITLE
Cannot Pick Random map in Favorite Maps List

### ISSUE THREAD

**Issue by AmethystCR** [CnCNet/xna-cncnet-client#380]

**Comment by devo1929** [comment]
Do you mean "Pick Random Map"? (not pickup)

**Comment by AmethystCR** [comment]
YES.



---Original---
From: ***@***.***&gt;
Date: Mon, Sep 26, 2022 08:20 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CnCNet/xna-cncnet-client] Cannot Pickup Random map in FavoriteMaps List (Issue #380)




 
Do you mean "Pick Random Map"? (not pickup)
