### ISSUE TITLE
[Bug Report] Cannot save client opinions when using filesettingdropdown or filesettingcheckbox section in OptionsWindow.ini.

### ISSUE THREAD

**Issue by AmethystCR** [CnCNet/xna-cncnet-client#381]
I cannot save client opinions when using custom filesettingdropdown and filesettingcheckbox section in OptionsWindow.ini, I'm not sure whether the problem is caused by CNCNET or Rampastring.Tools or Others. Here are relevant screenshots.

**Comment by AmethystCR** [comment]
filesettingdropdown not working, options can’t be saved!

**Comment by AmethystCR** [comment]
![屏幕截图 2022-11-10 185129](https://user-images.githubusercontent.com/80823938/201451032-3376bda8-55f2-47dc-8fc0-3e869f5a1dbc.png)
![屏幕截图 2022-11-10 185212](https://user-images.githubusercontent.com/80823938/201451034-57665872-ebad-4a47-95d7-638807675a3f.png)
![屏幕截图 2022-11-10 185321](https://user-images.githubusercontent.com/80823938/201451036-7572ade4-7253-42a4-a802-fa144cdb3522.png)

**Comment by frg2089** [comment]
It looks like it only supports folders, and I'm not sure if that's the right behavior.

To support file, you must used `SafePath.CombineFilePath` method.

https://github.com/CnCNet/xna-cncnet-client/blob/2fc20495f9e001555844c0a9383547661b159247/DTAConfig/Settings/FileSourceDestinationInfo.cs#L14-L16

**Comment by AmethystCR** [comment]
> 
The previous version supported the file replacement function. Will this function be added in the future? Otherwise, it can only be used in the old version. I hope it's just a bug.

**Comment by AmethystCR** [comment]
> It looks like it only supports folders, and I'm not sure if that's the right behavior.
> 
> To support file, you must used `SafePath.CombineFilePath` method.
> 
> https://github.com/CnCNet/xna-cncnet-client/blob/2fc20495f9e001555844c0a9383547661b159247/DTAConfig/Settings/FileSourceDestinationInfo.cs#L14-L16

I recompiled the client with this method, and now it works normally again. Thank you for your guidance.
