### ISSUE TITLE
The Main Menu music track can be heard after the client closes.

### ISSUE THREAD

**Issue by CCHyper** [CnCNet/xna-cncnet-client#399]
The Main Menu music track can be heard after the client closes.

- The music track plays for a variable amount of seconds after the client window closes.
- At roughly 1/3 of the time, the client binary process lingers in the background when closed, until the full menu track has been finished.

Both these issues can be observed if the client is run, and then ordered to close before the main menu shows, or a couple of seconds after the main menu shows.

Reproduced consistently on Windows 10.

**Comment by Rans4ckeR** [comment]
Can you run the launcher with these arguments and tell on which versions you have this issue?
`-DX`
`-OGL`
`-XNA`
`-UGL`

**Comment by Rans4ckeR** [comment]
@CCHyper can you post the log when it fails?

**Comment by Metadorius** [comment]
![image](https://user-images.githubusercontent.com/17500545/207301849-506817d4-424f-4c3b-b971-86c6534cf608.png)
I am not sure if that's related but I had those outputted in console today when I was working on translations and then closed the client.
