### ISSUE TITLE
Sending additional arbitrary data to players upon starting game

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#40]
Hello,

The idea is for a room host to ping an endpoint when starting the game.
The endpoint would return some arbitrary data like an ID. This would need to be shared with the other players in the room.

Upon a player returning from the game, they will have this ID.

What would be the best approach in sending custom data to other players like this?

**Comment by Rampastring** [comment]
Modify the START command and its handler.

START command sent by host: https://github.com/CnCNet/xna-cncnet-client/blob/master/DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs#L428

Command handler for non-host players: https://github.com/CnCNet/xna-cncnet-client/blob/master/DXMainClient/DXGUI/Multiplayer/GameLobby/CnCNetGameLobby.cs#L931
