### ISSUE TITLE
Understanding Client 

### ISSUE THREAD

**Issue by BySc** [CnCNet/xna-cncnet-client#41]
Hi, I'm started learning c# in my university and want to create client for ra2yr because client works better than original with windows 10 and ares.But I have few question
-- Project solution can create necessary ini,png files like the cncnet yuri client ?
-- Where can I find files list for client needed.
-- Im added new buildings but cncnet yuri client not see new buildings but when I try start game with ares works well.What I need to fix that ?

**Comment by Rampastring** [comment]
> -- Project solution can create necessary ini,png files like the cncnet yuri client ?
No, the project solution is only for building the main executable and the client libraries (Resources\clientdx.exe / clientxna.exe and Resources\(XNA)Binaries\ClientGUI.dll, ClientCore.dll, and DTAConfig.dll).

> -- Where can I find files list for client needed.
Which files the client "needs" depends highly on the game/mod in question. At minimum it needs at least Resources\ClientDefinitions.ini, INI\MPMaps.ini (the path of this file being customizable) and lots of graphics to be usable. In case you want to create a client for YR, you could just look at CnCNet YR files for a good reference. All the other target projects (Dawn of the Tiberium Age, Twisted Insurrection and Mental Omega) are good references as well.

> -- Im added new buildings but cncnet yuri client not see new buildings but when I try start game with ares works well.What I need to fix that ?
What do you mean with new buildings? The client isn't related to buildings in any way. In case you're attempting to mod CnCNet YR, it intentionally has some modding-related changes so mods wouldn't cause incompatibility issues between players.

For discussing YR modding, use https://forums.cncnet.org/index.php?board=112.0 or https://forums.cncnet.org/index.php?board=15.0
This repository is for the client generally, not specifically for YR.
