### ISSUE TITLE
launch issue

### ISSUE THREAD

**Issue by EazyServer** [CnCNet/xna-cncnet-client#42]
Any idea why I get this error?
I am trying to run it on VB on Mac Pro using Windows Vista

![untitled](https://cloud.githubusercontent.com/assets/19202935/22789428/cd229096-eeda-11e6-94b4-d8eb262b56fa.jpg)

**Comment by Rampastring** [comment]
Your system doesn't fill the minimum graphics card requirement. I'd guess VirtualBox emulates a GPU that has no 3D capabilities.

**Comment by GrantBartlett** [comment]
@EazyServer if it helps, Crossover emulating XP works well for me.

**Comment by EazyServer** [comment]
@Rampastring The game itself works just fine, both RA2 and YR!

**Comment by Rampastring** [comment]
The game doesn't need any 3D acceleration because it's ancient. However, the client does.
