### ISSUE TITLE
Volume showing as 10 even though it's set to 0

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#438]
**Report from a user:**

"Every time I set my audio settings to 0 either through the client or in-game and reboot the client, it shows as 10.
If you move the slider and switch it back to 0, it shows 0

The client sets it to 0 while the game sets the value to 0.000000, if I save the changes while on 10 it is 0 in settings, but the client still shows 10"

![image](https://user-images.githubusercontent.com/6104940/215326318-a51a8e98-5f67-4e51-901a-e0c245732447.png)

```
[Audio]
ClientVolume=0.4
PlayMainMenuMusic=False
StopMusicOnMenu=False
SoundVolume=0
VoiceVolume=0
ScoreVolume=0
IsScoreRepeat=no
IsScoreShuffle=True
SoundLatency=9
InGameMusic=yes
```

**Comment by devo1929** [comment]
To be clear, this is the label on the right of the slider. It continues to show a value that is inconsistent with the slider. After setting my client volume to 0 and restarting the client, these are the settings visually:
![image](https://user-images.githubusercontent.com/2062360/215328092-4d70e2c0-2294-4784-8ff7-c56f921f4834.png)
