### ISSUE TITLE
Client Request: Random Allied/Soviet

### ISSUE THREAD

**Issue by MJvst** [CnCNet/xna-cncnet-client#450]
We would like to see a "Random Allied/Soviet" Side in addition to the "Random" option under Side (Factions). This would allow players to get a random Soviet/Allied faction, as some times we'd like to play soviet & don't want to play Allied (& vice versa). This will also give a lot of variety to showmatches.

Examples have been attached (made by Polye). I believe he has been able to add a new house under GameOptions.ini to replicate this feature too.
![RandomAlliedSov](https://user-images.githubusercontent.com/97627274/224502083-0526ebe2-45ad-4bf0-be7d-0079ffbdf1af.jpg)

**Comment by AlperenFural** [comment]
I can do this. @Metadorius

**Comment by Rampastring** [comment]
The client can already do this, CnCNet YR just needs to be configured for this.

Please remake the issue at https://github.com/CnCNet/cncnet-yr-client-package

**Comment by MJvst** [comment]
cheers rampa
