### ISSUE TITLE
Adding support for non-hostname connections

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#46]
The issue described here: https://forums.cncnet.org/index.php?topic=7446.msg52811
The test build connects to the IP's of GameSurge servers directly and not the hostnames like "irc.gamesurge.net". 

The solution was to add IP's into the list of hostnames too. So incase the hostnames fail to connect, there's a backup option of IP's to connect to. It might even be better to list them as: 
```
"gamesurge", "irc.gamesurge.net",
"gamesurge-ip", "127.0.0.1", 

```etc

**Comment by Rampastring** [comment]
Are the GameSurge IP addresses static? If so, I'll implement this.

**Comment by GrantBartlett** [comment]
I believe so. The ones I added in the test were working from 6+ months ago. Just need to ping them and add.
