### ISSUE TITLE
Could not load file or assembly 'ClientUpdater, Version=1.0.13.0, Culture=neutral, PublicKeyToken=null'. Could not find or load a specific file. (0x80131621)

### ISSUE THREAD

**Issue by 285984303** [CnCNet/xna-cncnet-client#469]
---------------------------
KABOOOOOOOM
---------------------------
 has crashed. Error message:

Could not load file or assembly 'ClientUpdater, Version=1.0.13.0, Culture=neutral, PublicKeyToken=null'. Could not find or load a specific file. (0x80131621)

A crash log has been saved to the following file: 

D:\Code\Game\xna-cncnet-client-dev\DXMainClient\bin\Debug\Ares\Client\ClientCrashLogs\ClientCrashLog_2023_06_03_14_10.txt

If the issue is repeatable, contact the YR staff at and provide the crash log file.

**Comment by MahBoiDeveloper** [comment]
Where the `ClientCrashLog_2023_06_03_14_10.txt` file? Can you upload it?

**Comment by 285984303** [comment]
> Where the `ClientCrashLog_2023_06_03_14_10.txt` file? Can you upload it?

我回去找一下
