### ISSUE TITLE
[Bug][YR/RA2] Gametype meatgrind

### ISSUE THREAD

**Issue by mmtrt** [CnCNet/xna-cncnet-client#47]
Hello, meatgrind gametype is broken I used to play this with friends on old game before cncnet happened, now its not working in skirmish and online tried both and another thing sometimes it shows my customs maps then shows few maps excluding custom ones when selecting this gametype,
Also this game type limits tech used like troops buildings etc but its showing all the tech.

Can you guys look into this thanks.

**Comment by Rampastring** [comment]
@GrantBartlett YR is your territory.

**Comment by Metadorius** [comment]
Sounds like a client config problem and is probably fixed already, considering 3 years have passed. Closing.
