### ISSUE TITLE
How to log in with a Chinese name?

### ISSUE THREAD

**Issue by 285984303** [CnCNet/xna-cncnet-client#472]
How to log in with a Chinese name?

**Comment by MahBoiDeveloper** [comment]
Same as login on Russian - no way. You can play skirmish and singleplayer missions with localized nickname, but online you must have ascii-like nickname due to game engine limitations.

**Comment by 285984303** [comment]
Can you separate the login name from the display name?

**Comment by 285984303** [comment]
> Same as login on Russian - no way. You can play skirmish and singleplayer missions with localized nickname, but online you must have ascii-like nickname due to game engine limitations.就像在俄罗斯登陆一样-不可能。你可以用本地化的昵称来玩小冲突和单人任务，但是由于游戏引擎的限制，在线游戏你必须有类似ascii的昵称。

Can you separate the login name from the display name?

**Comment by 285984303** [comment]
> Same as login on Russian - no way. You can play skirmish and singleplayer missions with localized nickname, but online you must have ascii-like nickname due to game engine limitations.就像在俄罗斯登陆一样-不可能。你可以用本地化的昵称来玩小冲突和单人任务，但是由于游戏引擎的限制，在线游戏你必须有类似ascii的昵称。

Add a nickname that can be used for display

**Comment by 285984303** [comment]
![图片](https://github.com/CnCNet/xna-cncnet-client/assets/3397070/4f3ae945-a803-4166-8119-a6c1e4459111)

**Comment by Metadorius** [comment]
I don't think the IRC protocol which the client uses for online communication supports Unicode in names either. If you can prove otherwise please reopen the issue.

**Comment by 285984303** [comment]
> I don't think the IRC protocol which the client uses for online communication supports Unicode in names either, so it's impossible to do in a feasible manner. If you can prove otherwise please reopen the issue.我认为客户端用于在线通信的IRC协议也不支持名称中的Unicode，因此不可能以可行的方式这样做。如果你能证明不是这样，请重新讨论这个问题。

How can I support the display of Chinese names? How to build an IRC server? 那怎么才能支持中文名显示呢? IRC服务器怎么搭建?

**Comment by Metadorius** [comment]
1. We are not planning to switch to a custom IRC server.
2. I don't know.
3. This is not related to the client development.
