### ISSUE TITLE
Make `CNCNET_TUNNEL_LIST_URL` configurable via configuration file

### ISSUE THREAD

**Issue by SadPencil** [CnCNet/xna-cncnet-client#479]
```cs
public const string CNCNET_TUNNEL_LIST_URL = "http://cncnet.org/master-list";
```

Some Chinese players did report that they are struggling in connecting to multiplayer. And the cause is probably --- from my view --- that China's international firewall named GFW randomly blocks/interferes Cloudflare and so a proportion of users suffer. Making this URL configurable should help them set up a private server to support playing mods in China.

**Comment by pzhlkj6612** [comment]
+1. Making this URL configurable also helps people easily connect to tunnel servers for their own Mods.

**Comment by 285984303** [comment]
我试一下

**Comment by 285984303** [comment]
Well, many CN servers are gone

**Comment by SadPencil** [comment]
> 嗯 好多CN服务器都没有了

@285984303 This is a rude behavior. Do not use any language other than English in GitHub issue and also avoid comments in just one sentence. Express your words in detail so that others can get sufficient information about your comments. Never leave a comment like this.

**Comment by Metadorius** [comment]
Apart from setting up a private server (I think it's better to have a mirror for master list and master announce specifically) I agree, this also seems like an easy task to do.

**Comment by 285984303** [comment]
> Apart from setting up a private server (I think it's better to have a mirror for master list and master announce specifically) I agree, this also seems like an easy task to do.除了设置一个私人服务器（我认为最好有一个主列表和主公告的镜像），我同意，这似乎也是一个容易的任务。

When will it be updated?

**Comment by Metadorius** [comment]
I don't know, maybe @SadPencil wants to write a patch since I am currently bit busy with another stuff.

**Comment by SadPencil** [comment]
> I don't know, maybe @SadPencil wants to write a patch since I am currently bit busy with another stuff.

Well I probably will implement this patch seveal weeks later. This is not as urgent as we expected as the majority of mods have not successfully migrate the TSCv6 upgrade first and create private forks instead --- lack of detailed migration documentations. So even if I write a patch right now, these mod can not take advantage.

**Comment by 285984303** [comment]
> > I don't know, maybe @SadPencil wants to write a patch since I am currently bit busy with another stuff.
> 
> Well I probably will implement this patch seveal weeks later. This is not as urgent as we thought as the majority of mods have not successfully migrate the TSCv6 upgrade first and create private forks instead --- lack of detailed migration documentation. So even if I write a patch right now, these mods can not take advantage.
> 
> > 我不知道，也许@SadPencil想写一个补丁，因为我现在有点忙碌别的事情。
> 
> 好吧，我可能会实现这个补丁several周后。这并不像我们想象的那么紧迫，因为大多数MOD都没有成功地先迁移TSCv 6升级，然后创建私有fork--缺乏详细的迁移文档。所以即使我现在写一个补丁，这些mods也不能占便宜。

Was ist TSCv6?

**Comment by SadPencil** [comment]
> > > I don't know, maybe @SadPencil wants to write a patch since I am currently bit busy with another stuff.
> > 
> > 
> > Well I probably will implement this patch seveal weeks later. This is not as urgent as we thought as the majority of mods have not successfully migrate the TSCv6 upgrade first and create private forks instead --- lack of detailed migration documentation. So even if I write a patch right now, these mods can not take advantage.
> > > 我不知道，也许@SadPencil想写一个补丁，因为我现在有点忙碌别的事情。
> > 
> > 
> > 好吧，我可能会实现这个补丁several周后。这并不像我们想象的那么紧迫，因为大多数MOD都没有成功地先迁移TSCv 6升级，然后创建私有fork--缺乏详细的迁移文档。所以即使我现在写一个补丁，这些mods也不能占便宜。
> 
> Was ist TSCv6?

In other words, the majority of mods do not keep their codes up-to-date with upstream, i.e., this repo.

**Comment by 285984303** [comment]
> > > > I don't know, maybe @SadPencil wants to write a patch since I am currently bit busy with another stuff.
> > > 
> > > 
> > > Well I probably will implement this patch seveal weeks later. This is not as urgent as we thought as the majority of mods have not successfully migrate the TSCv6 upgrade first and create private forks instead --- lack of detailed migration documentation. So even if I write a patch right now, these mods can not take advantage.
> > > > 我不知道，也许@SadPencil想写一个补丁，因为我现在有点忙碌别的事情。
> > > 
> > > 
> > > 好吧，我可能会实现这个补丁several周后。这并不像我们想象的那么紧迫，因为大多数MOD都没有成功地先迁移TSCv 6升级，然后创建私有fork--缺乏详细的迁移文档。所以即使我现在写一个补丁，这些mods也不能占便宜。
> > 
> > 
> > Was ist TSCv6?
> 
> In other words, the majority of mods do not keep their codes up-to-date with upstream, i.e., this repo.

![图片](https://github.com/CnCNet/xna-cncnet-client/assets/3397070/af472c74-c1c9-4f98-ab6f-e09da928eebd)
Long time no update

**Comment by SadPencil** [comment]
@285984303 Would you please stop spamming this issue tracker? This is **not** the right place for practicing English, learning basic programming, or having a casual conversation. I have completely no interest in receiving a notification with merely meaningless screenshots or cringey sentences.
