### ISSUE TITLE
Replace TAL.DE.EU.GameSurge.net with LAN-Team.DE.EU.GameSurge.net

### ISSUE THREAD

**Issue by ThiefMaster** [CnCNet/xna-cncnet-client#489]
In particular the hardcoded IP (`195.8.250.180`) is problematic; I already updated the DNS so the old one points to its replacement. You may also want to remove other servers that no longer exist.

**Comment by ThiefMaster** [comment]
Why do you need to hardcode any IPs? Any reason against just using the DNS round-robin (`irc.gamesurge.net`)?

**Comment by SadPencil** [comment]
> Why do you need to hardcode any IPs or server names? Any reason against just using the DNS round-robin (`irc.gamesurge.net`)?
> 
> Ideally you'd use `irc.gamesurge.net` (with a fresh DNS lookup at least when a connection to the previous server fails), and any port from `6660,6666,6667,6668,6669` (they are open on all servers) with a preference on the standard `6667`.

I don't think `irc.gamesurge.net` is sufficient:
```
Name:    irc.gamesurge.net
Addresses:  162.248.94.123
          128.140.107.226
          192.223.27.109
          195.68.206.250
          188.240.145.60
```
```
Non-authoritative answer:
Name:    Krypt.CA.US.GameSurge.net
Address:  209.11.244.82
```

**Comment by SadPencil** [comment]
Closed as completed via d3486ad0c8966bf21ffff280c1efe1c90eecbc7f

**Comment by SadPencil** [comment]
> Why do you need to hardcode any IPs or server names? Any reason against just using the DNS round-robin (`irc.gamesurge.net`)?
> 
> Ideally you'd use `irc.gamesurge.net` (with a fresh DNS lookup at least when a connection to the previous server fails), and any port from `6660,6666,6667,6668,6669` (they are open on all servers) with a preference on the standard `6667`.

@ThiefMaster  Hi. It seems that only preserving `irc.gamesurge.net` causes some CnCNet YR users unable to connect, and it turns out these obsolete IPs work for them. Could you help us confirm that beyond the 5 servers from `irc.gamesurge.net`, which of these IP addresses are in use and which of them are not used anymore?

**Comment by ThiefMaster** [comment]
All the dead servers should be gone from `irc.gamesurge.net` now.

**Comment by MahBoiDeveloper** [comment]
> All the dead servers should be gone from `irc.gamesurge.net` now.

Still getting reconnected.

![Image](https://github.com/user-attachments/assets/c8302dd8-1d0c-4fe7-a9fa-7ad09162b748)

**Comment by ThiefMaster** [comment]
Getting randomly disconnected has nothing to do with this issue...

**Comment by Metadorius** [comment]
> Unless I'm missing something here, getting randomly disconnected has nothing to do with this issue...

I thought your response was in relation to the reconnection issues we started facing recently which we've been trying to contact you about. Purging dead servers didn't help resolve them.
