### ISSUE TITLE
Map preview shows only as a black square

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#5]
Potential fix untested: https://github.com/CnCNet/xna-cncnet-client/commit/845dc0372c5b68f868e74bbfa42b47d8be379643

**Comment by Rampastring** [comment]
I already briefly tested it in DTA and it works at least in most cases.

**Comment by GrantBartlett** [comment]
From some quick testing, this seems to be a confirmed fix.
