### ISSUE TITLE
Map Game Type field is open to abuse 

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#52]
Just spotted this on a custom map transfer, but this can happen anyway. 

When reading a map the client fills it as you would expect, but someone if someone is filling in the game mode with a domain name. There should probably be some sort of validation preventing this server side, but also client side?

![dodge](https://cloud.githubusercontent.com/assets/6104940/26527791/50bef3b0-4393-11e7-8616-b841e69d6c78.png)

**Comment by Rampastring** [comment]
Maybe the client should ignore all game modes on custom maps that don't already exist (in MPMaps.ini). Basically the default set of game modes would work as a whitelist for game modes, and all other game modes would be ignored.

**Comment by GrantBartlett** [comment]
Sounds like a good plan
