### ISSUE TITLE
Move SecondStageUpdater directory

### ISSUE THREAD

**Issue by SadPencil** [CnCNet/xna-cncnet-client#529]
Since .NET 6/7 migration, SecondStageUpdater resides in `Resources\Updater` directory. After merging ClientUpdater as well as SecondStageUpdater to this repo, it seems that we can just place SecondStageUpdater.exe (with dependencies) to `Resources\Binaries\Updater` directory to make the structure clean and neat

**Comment by Metadorius** [comment]
I agree it will be better since the updater is not a separate component anymore.

**Comment by Metadorius** [comment]
Though will need to account the possible need for double migration.
