### ISSUE TITLE
"Start New Game" doing nothing :(

### ISSUE THREAD

**Issue by vitaly-zdanevich** [CnCNet/xna-cncnet-client#540]
![image](https://github.com/CnCNet/xna-cncnet-client/assets/3514015/0a5547fb-1396-466e-8f74-b05c3e291c7d)

**Comment by Rampastring** [comment]
Closing as unrelated to the XNA/MonoGame CnCNet Client.

This looks like a game issue. You can find support from the CnCNet forums or CnCNet Discord server:
https://forums.cncnet.org/
https://discord.gg/teD428DyVG
