### ISSUE TITLE
Out of sync error

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#56]
Somewhere along the line this bug has appeared and I'm not sure how it's happened. 

1. I join someones game (receive a custom map from them), inherit their game settings, I then make my own game.
2. Wait for someone to join who doesn't have the map. Lock.
3. Start the game, it will always recon the game because one of the players (either me or the player joining) is out of sync and the game options have not refreshed. 

If we then play again without changing the map, its likely the same problem will happen.  If we change the map, the problem doesn't happen.

**Comment by GrantBartlett** [comment]
My spawn.ini 

```
[Settings]
Name=[neogrant]
Scenario=spawnmap.ini
UIGameMode=Duel
UIMapName=REDZONES ABC EPIC
PlayerCount=2
Side=3
IsSpectator=False
Color=2
CustomLoadScreen=Resources\l600s31.pcx
AIPlayers=0
Seed=1591652242
MapHash=c9f043dca096dbb431b348146522b79e2b1b6528
FrameSendRate=7
GameID=171710
Host=True
Port=-1592
Crates=True
ShortGame=True
AlliesAllowed=True
MCVRedeploy=True
MultiEngineer=False
BridgeDestroy=True
Superweapons=False
BuildOffAlly=True
Credits=10000
UnitCount=0
GameSpeed=0
Bases=Yes
FogOfWar=No
SidebarHack=Yes
AttackNeutralUnits=yes

[Tunnel]
Ip=46.166.187.82
Port=50000

[Other1]
Name=tomsons
Side=5
IsSpectator=False
Color=0
Ip=0.0.0.0
Port=2378

[SpawnLocations]
Multi1=2
Multi2=3

```

Tomsons spawn.ini

```
[Settings]
Name=tomsons
Scenario=spawnmap.ini
UIGameMode=Duel
UIMapName=REDZONES ABC EPIC
PlayerCount=2
Side=9
IsSpectator=False
Color=1
CustomLoadScreen=Resources\l600s91.pcx
AIPlayers=0
Seed=1291906261
MapHash=c9f043dca096dbb431b348146522b79e2b1b6528
FrameSendRate=7
GameID=171710
Host=False
Port=2378
Crates=True
ShortGame=True
AlliesAllowed=True
MCVRedeploy=True
MultiEngineer=False
BridgeDestroy=True
Superweapons=True
BuildOffAlly=True
Credits=10000
UnitCount=0
GameSpeed=0
Bases=Yes
FogOfWar=No
SidebarHack=Yes
AttackNeutralUnits=yes

[Tunnel]
Ip=46.166.187.82
Port=50000

[Other1]
Name=[neogrant]
Side=0
IsSpectator=False
Color=7
Ip=0.0.0.0
Port=-1592

[SpawnLocations]
Multi1=2
Multi2=0
```

**Comment by Rampastring** [comment]
I think I might have it figured out. I'll upload a fix soon.

**Comment by Rampastring** [comment]
Check if the latest 2 commits ( https://github.com/CnCNet/xna-cncnet-client/commit/716ed2f59626e7f9d623d97034fc5e19e34bbe30 and https://github.com/CnCNet/xna-cncnet-client/commit/4ee75621d2cdd63784ab25a782ddc93ba86a423b ) have fixed it.
