### ISSUE TITLE
Red Alert in French : sound "building" plays instead of "training" when creating infantry

### ISSUE THREAD

**Issue by Dasha-98** [CnCNet/xna-cncnet-client#573]
This issue concerns Red Alert.

In French, when an infantry is created, the sound played is "construction" (building) where it shall be "entraînement" (training).
The issue appears in the Online, LAN and Skirmish mode.
In offline mode (campaign or skirmish), the issue is not present.

**Comment by SadPencil** [comment]
Hi. Which mod do you play? CnCNet YR or something else? It's better to report this issue to the team that releases the mod since `xna-cncnet-client` does not manage the game artifacts.

**Comment by Dasha-98** [comment]
@SadPencil , I was just playing the original [Red Alert](https://cncnet.org/red-alert).

**Comment by SadPencil** [comment]
> @SadPencil , I was just playing the original [Red Alert](https://cncnet.org/red-alert).

You may click the link you have provided, and join the discord as the web page says. Then, find the right channel to report this issue in CnCNet discord server.
