### ISSUE TITLE
Having problems with Campaign launch

### ISSUE THREAD

**Issue by daverobertsfilm** [CnCNet/xna-cncnet-client#58]
So I've been trying to get the Campaign launch menu menu in the client.
I tried modifying the Mental Omega client, seeing as that is one that has it working, but when I change the details to my maps, it either doesn't launch or launches to the main menu.

I'm probably missing something really obvious, but is there any detail on what is required to get this working?

**Comment by tomsons26** [comment]
MO has a MO specific version of the spawner.

MO uses Ares, therefore it can't use a patched exe like the CnCNet games.
Ares uses Syringe, a DLL injector, while loading ares the ares-spawn.dll which contains our spawner code is injected as well.

The DLL has specific changes Speeder requested me to make so it can't be used for anything else.
On top of that as a dll the spawner code is extremely buggy, throwing to the main menu is actually a thing that happens to Speeder quite often.
Reason i suspect is the spawner is written in hacky mess of assembly, i've been trying to rewrite bits of it in C and fixing things in the process, maybe that in the future will make it stable enough for mods to use.

**Comment by Rampastring** [comment]
dkeeton uploaded this DLL as a generic cncnet5.dll spawner DLL that can be used with Ares.

As tomsons26 said though, don't be surprised if it has some issues.

https://drive.google.com/file/d/0B5PDmOO2fSv7VzJacjdvYmJpYkE/view

**Comment by daverobertsfilm** [comment]
Thanks for the heads up guys, the DLL seems to work perfectly, achieving exactly what I wanted. The only thing is now, it loads the mission in low res, not high res (ie 640x480).

**Comment by Rampastring** [comment]
Make sure that the settings file name that is written by the client matches what the filename that the game actually reads.

In other words, if the game reads for example RA2MD.ini, check that in \Resources\ClientDefinitions.ini the SettingsFile= key has "RA2MD.ini" as its value (without quotes).

**Comment by daverobertsfilm** [comment]
Ah, makes sense, got it working perfectly, thank you very much :)
