### ISSUE TITLE
[suggestion]make the client runs on macOS, Linux and etc.

### ISSUE THREAD

**Issue by CNAmira** [CnCNet/xna-cncnet-client#59]
MonoGame is available on macOS and Linux, so I think it'll be possible to run client on those platforms without wine.
I think it is worthy to make a 'native' client because both wine and mono can be cut into a very small size, that can make it to be distributed easily without depend on Microsoft's .Net Framework.

I have made some try to run on macOS but it refused to start up.
![screen shot 2017-09-10 at 2 31 12 pm](https://user-images.githubusercontent.com/4312700/30246727-c205384c-9634-11e7-8d45-1fc379be64c8.png)
![screen shot 2017-09-10 at 2 31 16 pm](https://user-images.githubusercontent.com/4312700/30246728-c2bf0d08-9634-11e7-9a44-43e1953df539.png)

**Comment by Rampastring** [comment]
I haven't really tried running the client on non-Windows platforms, nor do I have time for it in the near future, so I'm afraid I can't help much with it right now.

I think @dkeetonx got the client's OpenGL build to run natively on Linux, however.

**Comment by CNAmira** [comment]
I'd like to achieve it on my spare time, but I'm not familiar with C#.

**Comment by dkeetonx** [comment]
It does work on mono. The only problem is file separators and file system case-sensitivity assumption. Both are fixed if you launch the game like this:

env MONO_IOMAP=all mono --debug Resources/clientogl.exe

For DTA: In Resources/ClientDefinitions.ini you can change the game that gets executed: GameExecutableNames=wine-dta.sh

wine-dta.sh should be executable in $PATH and contain:

env WINEPREFIX=/path/to/.wine/ wine game.exe -SPAWN

**Comment by Kosti1** [comment]
I have made a guide on how to run mental omega in linux: https://hastebin.com/raw/metoqelewu

**Comment by CNAmira** [comment]
It does work! Thank you all.

**Comment by Rampastring** [comment]
Thanks for the guide @Kosti1. I'll try to simplify the process for future client versions (so that for example deleting the .wav files and editing ClientDefinitions.ini wouldn't be necessary).

**Comment by zpimp** [comment]
[ra2mo3-linux.zip](https://github.com/CnCNet/xna-cncnet-client/files/2305918/ra2mo3-linux.zip)

i have made some scripts to automate playing mental omega on linux
just put all files (game + mod + this) in a directory mo in drive_c in your wineprefix
run ./conf-mo.sh, and play from mo desktop shortcut
thanks @ghost for initial work

**Comment by danger89** [comment]
So..? where is the official Linux downloadable?  Eg. Red Alert Multiplayer is still Windows only:
https://cncnet.org/red-alert#download

**Comment by Muhammedramo** [comment]
hi

**Comment by andwan0** [comment]
> I have made a guide on how to run mental omega in linux: https://hastebin.com/raw/metoqelewu

Sorry for necro an old thread. But there's still a lack of linux instructions and this link is long dead gone :(

**Comment by Metadorius** [comment]
Latest client versions 2.11.x.x are runnable on Linux natively provided you have .NET 8 installed. All reference projects should ship with a script to launch the client, but if they aren't, look into `Resources/BinariesNET8/UniversalGL` (IIRC), you'll find an xplat binary there.

**Comment by andwan0** [comment]
Okay, seems WINEtricks only support up to .NET 7? or did you mean .NET 4.8?

**Comment by Metadorius** [comment]
I said *natively*, this means just running the file without any sorts of compatibility layers. You just need .NET 8 runtime for Linux installed.

**Comment by Metadorius** [comment]
Oh didn't see the edit. You're still doing it wrong. Please follow what I say, I didn't say anything about Wine, .NET Framework or Mono. For running the client you need only .NET 8 runtime for Linux, that's all.

**Comment by pzhlkj6612** [comment]
> ... but if they aren't, look into `Resources/BinariesNET8/UniversalGL` (IIRC), you'll find an xplat binary there.

Yes, it's `dotnet ./Resources/BinariesNET8/UniversalGL/clientogl.dll` .
