### ISSUE TITLE
Map transfers fails - player can still accept and play the game

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#6]
This then causes the following error:
[ClientCrashLog_3_12_2016_10_7.txt](https://github.com/CnCNet/xna-cncnet-client/files/628797/ClientCrashLog_3_12_2016_10_7.txt)

**Comment by Rampastring** [comment]
Fixed in https://github.com/CnCNet/xna-cncnet-client/commit/0c6c170bad42551c50cdc7168af81bd6542399c6

**Comment by GrantBartlett** [comment]
[ClientCrashLog_3_12_2016_11_55.txt](https://github.com/CnCNet/xna-cncnet-client/files/628825/ClientCrashLog_3_12_2016_11_55.txt)

**Comment by Rampastring** [comment]
That's a different issue, the client crashed when trying to extract the map from the ZIP file.

I'll close this issue because the player can no longer accept if the map is not valid, so the original issue is solved.
