### ISSUE TITLE
Keyboard info should be read from a INI

### ISSUE THREAD

**Issue by tomsons26** [CnCNet/xna-cncnet-client#62]
Instead of updating https://github.com/CnCNet/xna-cncnet-client/blob/master/DTAConfig/HotkeyConfigurationWindow.cs#L51 that mess every time a new key is added or a key is removed they should be read from a ini file.
That way the client only needs a INI update whenever we add new keys, remove them, or Ares adds new keys.
from RA2 info i have
enum MappableKeyCategories
{
    CATEGORY_CONTROL=0,
    CATEGORY_INFORMATION=1,
    CATEGORY_INTERFACE=2,
    CATEGORY_SELECTION=3,
    CATEGORY_TAUNT=4,
    CATEGORY_TEAM=5,
    CATEGORY_MISC=6,
    CATEGORY_DEBUG=7,
    CATEGORY_NUM_CATEGORIES=8
};
The INI could look like 
KeyboardDefaults.ini
```
;[KeyType]
;Name=foo
;Description=bar*some terminator maybe?*
;Category=CATEGORY_ ;one of MappableKeyCategories, or a string that is used for grouping for flexibility like the game modes in maps are grouped.
;DefaultKey=KEY ;Key value as number

;example
[ToggleAlliance]
Name=Alliance
Description=Toggle alliance with owner of selected object.
Category=CATEGORY_CONTROL
DefaultKey=65
```

**Comment by Rampastring** [comment]
Good idea.

**Comment by Rampastring** [comment]
Implemented: https://github.com/CnCNet/xna-cncnet-client/commit/10ec7e5bbb068dc24304ff196abbfadc63cbd5e8
