### ISSUE TITLE
Long game names not truncated

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#63]
![untitled](https://user-images.githubusercontent.com/6104940/31584391-5846e87e-b1a5-11e7-89d6-a9879ca68720.png)

**Comment by GrantBartlett** [comment]
Also profanity filter should probably be applied to game names (if not already)
![profanity](https://user-images.githubusercontent.com/6104940/31584402-bb6a9324-b1a5-11e7-9cdc-34b0eb08e96b.png)

**Comment by Rampastring** [comment]
https://github.com/CnCNet/xna-cncnet-client/commit/02bccd80c67fb056fafebee0b8101f64a6735c63

It could also be censored client-side if this is not enough.

**Comment by Rampastring** [comment]
This should fix the main issue https://github.com/CnCNet/xna-cncnet-client/commit/41055fa65937ba32c9c2bd32abfe098e9c1259b8
