### ISSUE TITLE
Fresh clone reveals modified files

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#66]
A little info: New pc, fresh git. No problems with other repos apart from this one.
I do a fresh clone, and have the following files as modified.

```       modified:   ClientCore/ClientCore.csproj
        modified:   ClientCore/CnCNet5/NameValidator.cs
        modified:   ClientCore/ProfanityFilter.cs
        modified:   DXMainClient/Domain/Multiplayer/MapLoader.cs
        modified:   DXMainClient/Domain/StatisticsSender.cs
        modified:   DXMainClient/Online/FileHashCalculator.cs
```

Try a fresh clone in a new folder, then do git status, and see if you get the same?

**Comment by Rampastring** [comment]
Just tried. I can't reproduce it.

**Comment by GrantBartlett** [comment]
It was git related. Had to change settings to checkout as it commit as is.
