### ISSUE TITLE
about HiddenStartingLocations suggestion last year

### ISSUE THREAD

**Issue by FELITH** [CnCNet/xna-cncnet-client#68]
make it depending on MaxPlayer= would be ok.
ex. MaxPlayer=3
only 1-3 will be displayed on the preview even 3-7(waypoint4-8) existed in the waypoints section.

no reason to skip numbers of available starting locations anyway. (it's weird when you have 1,4,7 only available. why skip the numbers, right)

**Comment by Rampastring** [comment]
Could you refresh my memory? I vaguely remember something about HiddenStartingLocations, but I can't remember why it was considered.

**Comment by FELITH** [comment]
> I don't want players to choose a point on the preview. that point is only for AI that spawning by "EnemyHouse0=".

for now, the drop-down selection of starting location is already depending on MaxPlayer=.
so I want the preview to do the same.

**Comment by Rampastring** [comment]
I can't remember which game you play (YR or MO, I'd guess), but this feature will be included in their next client update.
