### ISSUE TITLE
[suggestion] CSF file for custom map

### ISSUE THREAD

**Issue by FELITH** [CnCNet/xna-cncnet-client#69]
I don't know how the code works but I think it can be done by this simple way below.
 when launch the game, the Client will copy .csf with the same filename of .map file to the root directory by name "stringtable##.csf" so the game can read this file without players manually place them there.(this is why I make this suggestion. it's a little bit annoying for me or everyone I guess, to manually do these steps everytime when want to play the custom coop/mission maps.) when the game end, this copied .csf file will be delete.

if this came true. I think that the custom map will be more accessible for new players. and also increase the quality of maps for some author that didn't use .csf file because of manually place thing(see the result https://i.imgur.com/nEC4aPa.png xD).

csf file reference: https://www.modenc.renegadeprojects.com/CSF

**Comment by Rampastring** [comment]
As far as I know, the CnCNet map sharing service wouldn't automatically transfer there .csf files, so it wouldn't work optimally. You'd still have to manually transfer the map and the CSF.

**Comment by FELITH** [comment]
that service doesn't seem to works at all in MO. :/

**Comment by FELITH** [comment]
I just found that there is fix for this already in ARES

**Comment by tomsons26** [comment]
Its not a fix NOSTR has a 31 char limit
^ is already 39, beyond the limit it starts corrupting memory

**Comment by Rampastring** [comment]
Throwing another comment into this, better support for custom YR strings can't work properly with only client-side changes. It could be fixed either with Ares (NOSTR support for larger strings, I have no idea how easy / hard this is) or if the client added support for custom map-dependant CSF files, the CnCNet map sharing service would also have to support them.
