### ISSUE TITLE
ManagementObjectSearcher with Mono fails

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#75]
Generating an online id fails here for Mono. Much of ManagementObjectSearcher isn't yet implemented. 

https://github.com/mono/mono/blob/master/mcs/class/System.Management/System.Management/ManagementObjectSearcher.cs#L100

```
		public ManagementObjectCollection Get ()
		{
			throw new NotImplementedException ();
		}
```

**Comment by dkeetonx** [comment]
Fixed in e2b363b92e138d1572255237ec2dab50de1fa955
