### ISSUE TITLE
room popping sound stack up each other.

### ISSUE THREAD

**Issue by FELITH** [CnCNet/xna-cncnet-client#77]
it makes the sound too loud when more than one room pop up at the same time especially when you first join the lobby.

**Comment by FELITH** [comment]
talking about sound. is it bug that there is no clicking sound?

**Comment by Rampastring** [comment]
Button click sounds are trivial to add. So far no one has said that they'd have use for them though.

The stacking of the game discovery sound is indeed bad, I'll make it only play once in X seconds if / when I have time.

**Comment by Metadorius** [comment]
Think the issue was fixed some time ago. Closing.
