### ISSUE TITLE
Completing game, map defaults to first in map list

### ISSUE THREAD

**Issue by GrantBartlett** [CnCNet/xna-cncnet-client#8]
Upon completing a game, the map goes to the first map in the list, pauses, then goes back to the custom map.

**Comment by GrantBartlett** [comment]
Try it as a non host as I've only seen it happen as such, and with a custom map.

**Comment by Rampastring** [comment]
Check if it's fixed with https://github.com/CnCNet/xna-cncnet-client/commit/64292f34155ff9369303ca1448ec3a85f1ae6206
