### ISSUE TITLE
Fullscreen Client does not always correctly resize itself after a game ends.

### ISSUE THREAD

**Issue by dkeetonx** [CnCNet/xna-cncnet-client#80]
1. Run the client in fullscreen 1920x1080 
1. Spawn a game that will change the resolution to 1600x900
1. Desktop resets back to 1920x1080 after the game finishes

Some of the time the client will be resized 1600x900 window and will not fullscreen itself.

**Comment by Rampastring** [comment]
I'd expect https://github.com/CnCNet/xna-cncnet-client/commit/fdd1f6c23b85521770a00d905740d364e29c7343 to have fixed this.
