### ISSUE TITLE
Common issues of MO

### ISSUE THREAD

**Issue by FELITH** [CnCNet/xna-cncnet-client#89]
1."Lag"
this is like almost 100% occurred on Windows8-10
Why not set TS-DDRAW as default for them?

2.You have to run MO Client as Admin on Windows8-10
maybe point the player out that the client isn't running as admin?

**Comment by Rampastring** [comment]
> 2.You have to run MO Client as Admin on Windows8-10

That's not true.

> this is like almost 100% occurred on Windows8-10
> Why not set TS-DDRAW as default for them?

TS-DDRAW is the default renderer on Windows 8 and 10.

This is not the correct forum for Mental Omega feedback btw. This is for client development in general, not a Mental Omega repository. No one of MO's devs reads this actively (as far as I know). If you have feedback specific to Mental Omega, you should use their forums instead: https://forums.revora.net/forum/385-mental-omega-apyr/

**Comment by FELITH** [comment]
okay thx maybe it's the ares issue, the run admin
